### ISSUE TITLE
Azure Cosmos DB support

### ISSUE THREAD

**Issue by goransss** [automatiko-io/automatiko-engine#222]
Azure Cosmos DB is compatible with most of the MongoDB API. 

I tried connecting to it using the MongoDB persistence add-on and got the following error on startup:
com.mongodb.MongoCommandException: Command failed with error 115 (CommandNotSupported): ''text' is not supported' on server [automatiko-test-swedencentral.mongo.cosmos.azure.com:10255](http://automatiko-test-swedencentral.mongo.cosmos.azure.com:10255/). The full response is {"ok": 0.0, "errmsg": "'text' is not supported", "code": 115, "codeName": "CommandNotSupported"}

The same project works fine with MongoDB.

I think the issue is with the evaluation query operator text not being supported. See the compatibility matrix:
https://docs.microsoft.com/en-us/azure/cosmos-db/mongodb/feature-support-40#evaluation-query-operators

However, I don't have deep enough knowledge about Automatiko to determine if it is possible to switch to the regex operator or if other changes are needed.

The whole stacktrace is attached below.

[cosmosdb-stacktrace.log](https://github.com/automatiko-io/automatiko-engine/files/8178399/cosmosdb-stacktrace.log)

**Comment by mswiderski** [comment]
just managed to test it with newly created Azure Cosmos DB with MongoDB Api and it works as expected with the linked pull request.

**Comment by goransss** [comment]
@mswiderski  Thanks, it worked great when I finally got the time to test it out. (Had some sick children to deal with today)

Cheers

**Comment by mswiderski** [comment]
thanks for confirming @goransss 

glad it works as expected now. Interesting use case, never thought about going for azure cosmos db :)
