### ISSUE TITLE
Unable to use MongoDB with native build

### ISSUE THREAD

**Issue by goransss** [automatiko-io/automatiko-engine#230]
When trying to build a native docker image with the MongoDB dependency I get the following error.

[mongodb-native-build-fail.log](https://github.com/automatiko-io/automatiko-engine/files/8361185/mongodb-native-build-fail.log)
 
If I comment out the MongoDB dependency the build completes successfully. Also, the non-native builds work fine with MongoDB.

I'm using Automatiko version 0.13.0

**Comment by mswiderski** [comment]
@goransss thanks for reporting it.

As a quick workaround could you please try to add following dependency:

````
    <dependency>
      <groupId>com.github.jnr</groupId>
      <artifactId>jnr-unixsocket</artifactId>
      <version>0.24</version>
    </dependency>
````

I will investigate further what caused this to be not on class path but still being required by mongo client.

**Comment by goransss** [comment]
Thanks, the quick fix worked like a charm.

**Comment by mswiderski** [comment]
great to hear, will keep the issue open until further investigation is done

**Comment by mswiderski** [comment]
alternative (and I think better approach) is to remove `--report-unsupported-elements-at-runtime` from pom.xml configuration to the profile for native image

Please locate `<quarkus.native.additional-build-args>` and remove `--report-unsupported-elements-at-runtime` from it. That should allow you to build native image with mongo and there won't be any need to include this extra dependency.

**Comment by goransss** [comment]
Thanks, I will give it a try.

**Comment by mswiderski** [comment]
I have confirmed that removing `--report-unsupported-elements-at-runtime` flag is the preferred way.

Will move the flag from archetypes and that will close this issue.
